src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\PrePersist;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Veuillez entrer une date valide ")
     * @Assert\GreaterThan("today" ,  message="La date d'arrivée doit être ultérieure à la date d'aujourd'hui !", groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Veuillez entrer une date valide ")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doit être superieur à la date d'arrivée !")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    public function getId() : ? int
    {
        return $this->id;
    }

    public function getBooker() : ? User
    {
        return $this->booker;
    }

    public function setBooker(? User $booker) : self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd() : ? Ad
    {
        return $this->ad;
    }

    public function setAd(? Ad $ad) : self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate() : ? \DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate) : self
    {
        $this->startDate = $startDate;

        return $this;
    }


    public function getEndDate() : ? \DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate) : self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt() : ? \DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt) : self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount() : ? float
    {
        return $this->amount;
    }

    public function setAmount(float $amount) : self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment() : ? string
    {
        return $this->comment;
    }

    public function setComment(? string $comment) : self
    {
        $this->comment = $comment;

        return $this;
    }

    /**
     * Permet d'enregister des champs dans la base automatiquement
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function prePersist()
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }

        if (empty($this->amount)) {
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }

    }

    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function isBookableDates()
    {
        $noteAvailableDays = $this->ad->getNotAvailableDays();

        $bookingDays = $this->getDays();

        $formatDay = function ($day) {
            return $day->format('Y-m-d');
        };

        // Tableau des chaines de caractères de mes journées
        $days = array_map($formatDay, $bookingDays);

        // Tableau des chaines de caractères de mes journées
        $notAvailable = array_map($formatDay, $noteAvailableDays);

        dump($notAvailable);
        //die;

        foreach ($days as $day) {
            if (array_search($day, $notAvailable) !== false) {
                return false;
            }
        }
        return true;
    }

    /**
     * Permet de récupérer un tableau des days qui correspondent à ma reservation
     * 
     */
    public function getDays()
    {
        $notAvailableDays = [];
        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );

        $days = array_map(function ($daysTimestamp) {
            return new \DateTime(date('Y-m-d', $daysTimestamp));
        }, $resultat);

        $notAvailableDays = array_merge($notAvailableDays, $days);

        return $notAvailableDays;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;

use Symfony\Component\Validator\Constraints as Assert;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Un autre utilisateur possede déjà cet email merci de la modifier"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(
     *      message = "Le prénom ne doit pas être vide"
     * )
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     *  @Assert\NotBlank(
     *      message = "Le nom ne doit pas être vide"
     * )
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message = "Veuillez renseigner un email valide")
     * 
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(
     *      message = "Renseigner un url d'avatar valide."
     * )
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(
     *      propertyPath = "hash",
     *      message = "Les deux mots de passes ne sont pas identiques."
     * )
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 10,
     *      minMessage = "Votre introduction doit avoir plus de  {{ limit }} caractères"
     * )
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * 
     * @Assert\Length(
     *      min = 10,
     *      minMessage = "Votre déscription doit avoir plus de  {{ limit }} caractères"
     * )
     * 
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author", orphanRemoval=true)
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId() : ? int
    {
        return $this->id;
    }

    public function getFirstName() : ? string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName) : self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName() : ? string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName) : self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail() : ? string
    {
        return $this->email;
    }

    public function setEmail(string $email) : self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture() : ? string
    {
        return $this->picture;
    }

    public function setPicture(? string $picture) : self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash() : ? string
    {
        return $this->hash;
    }

    public function setHash(string $hash) : self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getPasswordConfirm() : ? string
    {
        return $this->passwordConfirm;
    }

    public function setPasswordConfirm(string $passwordConfirm) : self
    {
        $this->passwordConfirm = $passwordConfirm;

        return $this;
    }



    public function getIntroduction() : ? string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction) : self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription() : ? string
    {
        return $this->description;
    }

    public function setDescription(string $description) : self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug() : ? string
    {
        return $this->slug;
    }

    public function setSlug(string $slug) : self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds() : Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad) : self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad) : self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     */
    public function initialiseSlug()
    {
        if (empty($this->slug)) {
            $slug = new Slugify();
            $this->slug = $slug->slugify($this->firstName . ' ' . $this->lastName);
        }
    }


    /*
     *Les fonctions implementées par l'interface userInterface
     */

    public function getRoles()
    {
        $roles = $this->userRoles->map(function ($role) {
            return $role->getTitle();
        })->toArray();

        $roles[] = "ROLE_USER";

        return $roles;

    }

    public function getPassword()
    {
        return $this->hash;
    }

    public function getSalt()
    {
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
    }

    public function getFullName()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles() : Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole) : self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole) : self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad, Request $request, ObjectManager $manager)
    {

        $booking = new Booking();

        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user = $this->getUser();
            $booking->setBooker($user)
                ->setAd($ad);

                //Si les dates ne sont pas disponibles, message d'erreur
            if (!$booking->isBookableDates()) {
                $this->addFlash(
                    'warning',
                    "Les dates que vous avez choisi ne peuvent pas être réservées : elles sont déjà prises."
                );
            } else {
                $manager->persist($booking);
                $manager->flush();

                return $this->redirectToRoute('booking_show', ['id' => $booking->getId(), 'withAlert' => 'true']);
            }
        }


        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }


    /**
     * @Route("/booking/{id}", name="booking_show")
     * @Security("is_granted('ROLE_USER') and user === booking.getBooker()", message= "Cette réservation ne vous apartient pas , vous ne pouvez pas la voir")
     */
    public function show(Booking $booking, Request $request, ObjectManager $manager)
    {
        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setAd($booking->getAd())
                ->setAuthor($this->getUser());

            $this->addFlash(
                'success',
                "Votre commentaire a bien été pris en compte"
            );

            $manager->persist($comment);
            $manager->flush();

        }


        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form' => $form->createView()
        ]);
    }

}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation de l'annonce:
    {{ ad.title }}
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css"/>
{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="h2 md-4 mt-4">Réservation de l'annonce:<em>{{ ad.title }}</em>
        </h1>
        <p class="md-4">Vous êtes sur le point de réserver le bien de
            <b>{{ ad.author.fullName }}</b>, dites nous tout, on s'occupe de reste !</p>

        {{ form_start(form)}}
        <div class="alert alert-light">
            <h4 class="my-4">Quelles sont vos dates qui vous intéressent
            </h4>
            <div class="row mt-4">
                <div class="col">{{form_row(form.startDate) }}</div>
                <div class="col">{{form_row(form.endDate) }}</div>

            </div>

            <h4 class="my-4">Montant du séjour :<span id="amount"></span>&euro;</h4>

            <span id="days">
                1&nbsp;

            </span>
            nuit(s) à
            {{ad.price | number_format( 2,',', ' ' ) }}
            &euro; par nuit</span>

        <h4 class="my-5">Vous avez un commentaire ?</h4>
        {{form_widget(form.comment)}}

        <button type="submit" class="btn btn-success mt-4">
            Je réserve</button>

        {{ form_end(form)}}
    </div>

</div>
{% endblock %}

{% block javascripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.fr.min.js"></script>

<script>
    $(document).ready(function () {
        $('#booking_startDate, #booking_endDate').datepicker({
            format: 'dd/mm/yyyy',
            language: 'fr',
            datesDisabled: [
                {% for day in ad.notAvailableDays %}
                    "{{ day.format('d/m/Y') }}",
                {% endfor %}
            ],
            startDate: new Date()
        });

        $('#booking_startDate, #booking_endDate').on('change', calculateAmount);

    });

    function calculateAmount() {
        //on chope les dates
        const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
        const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

        if (startDate && endDate && startDate < endDate) {
            const DAY_TIME = 24 * 60 * 60 * 1000;
            const interval = endDate.getTime() - startDate.getTime();
            const days = interval / DAY_TIME;

            const amount = days * {{ ad.price }};

            $("#days").text(days);
            $("#amount").text(amount.toLocaleString('fr-FR'));

        }

    }
</script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}booking Numéro :
    {{ booking.id }}
{% endblock %}

{% block body %}

    {% set ad = booking.ad %}

    {% set user = ad.author %}

    <div class="container">
        <h1>Votre réservation (n°{{ booking.id }})</h1>

        {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">

                <h4 class="alert-heading">
                    Bravo!
                </h4>
                <p>Votre réservation auprès de
                    <strong>
                        <a href="{{ path('user_show', {'slug' : user.slug}) }}">{{ user.fullName}}</a>
                    </strong>
                    pour l'annonce :
                    <strong>
                        <a href="{{ path('ads_show', {'slug' : ad.slug}) }}">{{ad.title}}</a>
                    </strong>
                    a bien été prise en compte.
                </p>
            </div>

        {% endif %}

        <div class="row mb-3">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Détails</h2>
                    <dl class="row">
                        <dt class="col-md-4">Numéro</dt>
                        <dd class="col-md-8">{{ booking.id }}</dd>
                        <dt class="col-md-4">Date d'arrivée</dt>
                        <dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
                        <dt class="col-md-4">Date de départ</dt>
                        <dd class="col-md-8">{{ booking.endDate| date('d/m/Y') }}</dd>
                        <dt class="col-md-4">Nombre de nuit</dt>
                        <dd class="col-md-8">{{ booking.duration }}</dd>
                        <dt class="col-md-4">Montant Total</dt>
                        <dd class="col-md-8">{{ booking.amount  | number_format( 2,',', ' ' ) }}&euro;</dd>
                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{ booking.comment | default('Aucun commentaire') }}</dd>
                    </dl>

                    <hr>
                    <h2 class="alert-heading">Votre Hôte</h2>

                    <div class="row">
                        <div class="col-3">
                            <img src="{{ user.picture }}" class="avatar avatar-medium" alt="Avat de {{user.fullName }}">
                        </div>
                        <div class="col">
                            <h4>
                                <a href="{{ path('user_show', {'slug' : user.slug}) }}">{{ user.fullName}}</a>
                            </h4>
                            <span class="badge badge-primary">{{ user.ads|length }}
                                annonces</span>

                        </div>
                    </div>
                </div>
                {{user.description |raw}}

                <a href="{{ path('user_show', {'slug' : user.slug}) }}" class="btn btn-primary">Plus d'info sur
                    {{ user.firstName }}</a>

                <div class="alert alert-light">
                    <h2 class="alert-heading" id="comment">Votre commentaire compte !</h2>

                    {% if date() > date(booking.endDate) %}
                        {% set comment = booking.ad.commentFromAuthor(app.user) %}

                        {% if comment is not null %}
                            <blockquote>
                                {{ comment.content }}
                            </blockquote>
                            <strong>
                                Note:
                            </strong>
                            {% include 'partials/rating.html.twig' with {
                                'rating' : comment.rating
                            } %}
                        {% else %}
                            {{ form_start(form) }}
                            {{ form_widget(form) }}
                            <button type="submit" value="" class="btn btn-success">Confirmer !</button>
                            {{ form_end(form) }}

                        {% endif %}

                    {% else %}
                        <p>Vous ne pouvez pas laisser un commentaire pour le moment.</p>
                    {% endif %}

                </div>
            </div>
            <div class="col">
                <div class="alert alert-light">
                    <h2 class="alert-heading">Votre hébergement</h2>

                    <h4>
                        <a href="{{ path('ads_show', {'slug' : ad.slug}) }}">{{ad.title}}</a>
                    </h4>
                    <img src="{{ ad.coverImage }}" alt="{{ad.title}}" class="img-fluid">
                    {{ad.content|raw}}
                    <a href="{{ path('ads_show', {'slug' : ad.slug}) }}" class="btn btn-primary">Plus d'info sur L'annonce</a>
                </div>

            </div>
        </div>

    </div>
{% endblock %}